#!/bin/bash

TMP_STAGING=".tmp_staging"

CONFIG_FILE=$(dirname $0)/config
if [ -e $CONFIG_FILE ]; then
    . $CONFIG_FILE
fi

if [ ! -x $PHPCS_BIN ]; then
    echo "PHP CodeSniffer bin not found or executable -> $PHPCS_BIN"
    exit 1
fi

if git rev-parse --verify HEAD
then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- )

if [ "$FILES" == "" ]; then
    exit 0
fi

# create temporary copy of staging area
if [ -e $TMP_STAGING ]; then
    rm -rf $TMP_STAGING
fi
mkdir $TMP_STAGING

FILES_TO_CHECK=""
for FILE in $FILES
do
    echo "$FILE" | egrep -q "$PHPCS_FILE_PATTERN"
    RETVAL=$?
    if [ "$RETVAL" -eq "0" ]
    then
        FILES_TO_CHECK="$FILES_TO_CHECK $FILE"
    fi
done

if [ "$FILES_TO_CHECK" == "" ]; then
    exit 0
fi

if [ "$PHPCS_IGNORE" != "" ]; then
    IGNORE="--ignore=$PHPCS_IGNORE"
else
    IGNORE=""
fi

if [ "$PHPCS_SNIFFS" != "" ]; then
    SNIFFS="--sniffs=$PHPCS_SNIFFS"
else
    SNIFFS=""
fi

if [ "$PHPCS_ENCODING" != "" ]; then
    ENCODING="--encoding=$PHPCS_ENCODING"
else
    ENCODING=""
fi

if [ "$PHPCS_IGNORE_WARNINGS" == "1" ]; then
    IGNORE_WARNINGS="-n"
else
    IGNORE_WARNINGS=""
fi

STAGED_FILES=""
ORIGINAL_FILES=""
for FILE in $FILES_TO_CHECK
do
  ID=$(git diff-index --cached $against $FILE | cut -d " " -f4)

  mkdir -p "$TMP_STAGING/$(dirname $FILE)"
  git cat-file blob $ID > "$TMP_STAGING/$FILE"
  STAGED_FILES="$STAGED_FILES $TMP_STAGING/$FILE"
  ORIGINAL_FILES="$ORIGINAL_FILES $FILE"
done

OUTPUT=$(php $PHPCS_BIN -s $IGNORE_WARNINGS --standard=$PHPCS_CODING_STANDARD $ENCODING $IGNORE $SNIFFS $STAGED_FILES)
RETVAL=$?

if [ $RETVAL -ne 0 ]; then
    echo "$OUTPUT" | less

	exec < /dev/tty

	while true; do
	  read -p "Auto fix with phpcbf(not recommended if file has a lot errors)? (Y/n) " yn
	  case $yn in
		  [Yy] ) 
			php $PHPCBF_BIN $ORIGINAL_FILES --standard=$PHPCS_CODING_STANDARD;
			echo "Files errors fixed re-add them";
			rm -rf $TMP_STAGING
			git add $ORIGINAL_FILES
			break;;
		  [Nn] ) break;;
		  * ) echo "Please answer y or n for yes or no.";;
	  esac
	done

	exec < /dev/tty

	while true; do
	  read -p "Are you want continue commit? (Y/n) " yn
	  case $yn in
		  [Yy] ) exit 0;;
		  [Nn] ) break;;
		  * ) echo "Please answer y or n for yes or no.";;
	  esac
	done
fi


# delete temporary copy of staging area
rm -rf $TMP_STAGING

exit $RETVAL